spring:
  h2:
    console:
      enabled: true
      path: /h2
      connection-test-query: SELECT 1 FROM DUAL
      auto-commit: true
  datasource:
    url: jdbc:h2:mem:introKotlin;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;INIT=RUNSCRIPT FROM 'classpath:sql/create.sql'
